<?php
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
	'key' => 'group_579009cee0d25',
	'title' => 'Shows',
	'fields' => array (
		array (
			'key' => 'field_57900bba41553',
			'label' => 'Date',
			'name' => 'date',
			'type' => 'date_picker',
			'instructions' => 'Date of the event',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'display_format' => 'm/d/Y',
			'return_format' => 'd/m',
			'first_day' => 0,
		),
		array (
			'key' => 'field_579009dbddda1',
			'label' => 'Time',
			'name' => 'time',
			'type' => 'text',
			'instructions' => 'Time of show (e.g. 9:30 PM, 10:00 AM)',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_57900a5dddda2',
			'label' => 'Venue',
			'name' => 'venue',
			'type' => 'text',
			'instructions' => 'Name of venue',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_57900a8addda3',
			'label' => 'Location',
			'name' => 'location',
			'type' => 'text',
			'instructions' => 'Location of venue (e.g. Boston, MA or Las Vegas, NV)',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_57900ac6ddda4',
			'label' => 'Venue Link',
			'name' => 'venue_link',
			'type' => 'url',
			'instructions' => 'Link to the venue\'s website, ideally directly to the page where attendees can purchase tickets',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
		array (
			'key' => 'field_57900af0ddda5',
			'label' => 'Venue Logo',
			'name' => 'venue_logo',
			'type' => 'image',
			'instructions' => 'Venue\'s logo, if available',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'show',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
		0 => 'the_content',
		1 => 'excerpt',
	),
	'active' => 1,
	'description' => '',
));

endif;
